version: '3.8'

networks: 
  jnb-kafka:
    name: jnb-kafka

services:
  jnb-zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    networks:
      - jnb-kafka
    ports:
      - '2181:2181'
    volumes:
      - 'jnb-zookeeper-data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  jnb-kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    networks:
      - jnb-kafka
    hostname: jnb-kafka-01
    ports:
      - '19092:19092'
    volumes:
      - 'jnb-kafka-data:/bitnami'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka_jnb-kafka_1:9092,CONNECTIONS_FROM_HOST://localhost:19092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://jnb-kafka-01:9092,CONNECTIONS_FROM_HOST://jnb-kafka-01:19092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=jnb-zookeeper:2181
    depends_on:
      - jnb-zookeeper
  jnb-kowl:
    image: quay.io/cloudhut/kowl:v1.2.0
    networks:
      - jnb-kafka
    restart: on-failure
    hostname: jnb-kowl
    volumes:
    - ./files/config.yaml:/etc/kowl/config.yaml
    ports:
    - "18084:8080"
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    depends_on:
      - jnb-kafka

volumes:
  jnb-zookeeper-data:
    driver: local
  jnb-kafka-data:
    driver: local